services:
  mcl-stratum:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
      args:
        RPC_USER: ${rpcuser}
        RPC_PASS: ${rpcpass} 
        WALLET: ${address}
    container_name: mcl-stratum
    environment:
      RPC_USER: ${rpcuser}
      RPC_PASS: ${rpcpass}
      PUBKEY: ${pubkey}
    ports:
      - "33824:33824" # p2p port
      - "8888:8888"  # make same port inside equihash.conf
    volumes:
      - ./equihash.conf:/home/mclminer/equihash.conf
      - ./mcldata:/home/mclminer/.komodo/MCL
      - ./zcashparams:/home/mclminer/.zcash-params
    command: ./yiimp-stratum-equihash/stratum equihash